### ISSUE TITLE
Bug: For WEEKLY recurrences neither BYMONTHDAY nor BYYEARDAY may appear

### ISSUE THREAD

**Issue by n8rade** [etesync/etesync-web#134]
I was messing around with a recurring schedule and was trying to decide if I wanted to do it monthly, weekly, or bi/tri-weekly on a certain day of the week. I had Su selected and switched to weekly to save it. This occurred right after. I do not have the ability to do anything besides view this screen.

```
Something went wrong!
For WEEKLY recurrences neither BYMONTHDAY nor BYYEARDAY may appear
Error: For WEEKLY recurrences neither BYMONTHDAY nor BYYEARDAY may appear
    at e.init (https://calendar.local/static/js/2.cca63d69.chunk.js:2:73875)
    at e.fromData (https://calendar.local/static/js/2.cca63d69.chunk.js:2:73286)
    at new e (https://calendar.local/static/js/2.cca63d69.chunk.js:2:72396)
    at ICAL.Recur.iterator (https://calendar.local/static/js/2.cca63d69.chunk.js:2:68682)
    at n._init (https://calendar.local/static/js/2.cca63d69.chunk.js:2:91528)
    at n.fromData (https://calendar.local/static/js/2.cca63d69.chunk.js:2:89324)
    at new n (https://calendar.local/static/js/2.cca63d69.chunk.js:2:88986)
    at t.iterator (https://calendar.local/static/js/2.cca63d69.chunk.js:2:94530)
    at https://calendar.local/static/js/main.80d3df9b.chunk.js:1:152641
    at Array.forEach (<anonymous>)
```

It seems I can log out and possibly log into a different user, but I only have one user setup currently. Is there anyway to fix this without losing all my progress? Am I able to delete the recurring event manually somehow?

Let me know if there's some formatting rules I'm missing or information needed from me!

Note: Restarting nginx or the etesync server stack (uwgsi + django) did nothing to fix this.

**Comment by n8rade** [comment]
I just found the Change Journals in the Android App. I am unable to access the same page in the Web Client. I believe I can roll back there. Let me know if there's anything I can do to contribute before rolling back.

**Comment by tasn** [comment]
Please roll-back and let me know if it makes it work again for you.
There's enough information in this ticket for me to figure out what's wrong without needing anything else, though I'm interested to hear if the above makes it work again.

**Comment by n8rade** [comment]
On the Android App, I was able to restore the state of a previous change for the offending calendar entry. After hitting the sync button and giving it a little bit, I am able to successfully use the web client again without issue.

Let me know if you need anything else. Otherwise, this is resolved on my end. Glad to know I have a way out if I run into anything weird again!

**Comment by tasn** [comment]
Great to hear it fixed it for you. @Tal-Leibman is going to take a look at it tomorrow and fix the underlying issue.

Thanks again for all the info!

**Comment by tasn** [comment]
Fixed. Could you please confirm it's also fixed for you? I'm closing it for now, please reopen if it isn't.

**Comment by n8rade** [comment]
I've pulled the latest build from https://client.etesync.com/etesync-web.tgz and now cannot seem to make any recurring events. I can make the event itself, but it does not multiply visually on the calendar view. Even trying to make a daily recurring event with nothing special doesn't work.

**Comment by tasn** [comment]
I just reverted the other changes and pushed another fix. I hope it'll solve it, it works here.

Could you please confirm?

**Comment by n8rade** [comment]
Have a couple of things for you.

1. Recurring Events appears to be mostly working.
2. When choosing a monthly recurring event, I am unable to select a integer day and save it properly. If I type in 20 (to have to occur on the 20th of the month), I can save it and then it doesn't maintain that number. Not sure if this is being reset somewhere accidentally.
3. When testing out the 2nd item, I switched to "Yearly" and ran into this:
Something went wrong!
Material-UI: the `value` prop must be an array when using the `Select` component with `multiple`.
Error: Material-UI: the `value` prop must be an array when using the `Select` component with `multiple`.
    at https://calendar.local/static/js/2.cca63d69.chunk.js:2:1559128
    at L (https://calendar.local/static/js/2.cca63d69.chunk.js:2:1107450)
    at e (https://calendar.local/static/js/2.cca63d69.chunk.js:2:1106680)
    at e (https://calendar.local/static/js/2.cca63d69.chunk.js:2:1106803)
    at R (https://calendar.local/static/js/2.cca63d69.chunk.js:2:1107145)
    at N (https://calendar.local/static/js/2.cca63d69.chunk.js:2:1107792)
    at Object.map (https://calendar.local/static/js/2.cca63d69.chunk.js:2:1108112)
    at https://calendar.local/static/js/2.cca63d69.chunk.js:2:1559034
    at Wi (https://calendar.local/static/js/2.cca63d69.chunk.js:2:1162153)
    at yo (https://calendar.local/static/js/2.cca63d69.chunk.js:2:1168023)
I am able to recover from this, but still run into it every time I try to pick Yearly.
4. After recovering, I had Monthly selected and chose Mon,Tue,Wed and hit save.
5. Then, I selected Weekly again and ran into:
Something went wrong!
For WEEKLY recurrences neither BYMONTHDAY nor BYYEARDAY may appear
Error: For WEEKLY recurrences neither BYMONTHDAY nor BYYEARDAY may appear
    at e.init (https://calendar.local/static/js/2.cca63d69.chunk.js:2:73875)
    at e.fromData (https://calendar.local/static/js/2.cca63d69.chunk.js:2:73286)
    at new e (https://calendar.local/static/js/2.cca63d69.chunk.js:2:72396)
    at ICAL.Recur.iterator (https://calendar.local/static/js/2.cca63d69.chunk.js:2:68682)
    at n._init (https://calendar.local/static/js/2.cca63d69.chunk.js:2:91528)
    at n.fromData (https://calendar.local/static/js/2.cca63d69.chunk.js:2:89324)
    at new n (https://calendar.local/static/js/2.cca63d69.chunk.js:2:88986)
    at t.iterator (https://calendar.local/static/js/2.cca63d69.chunk.js:2:94530)
    at https://calendar.local/static/js/main.ea52be7d.chunk.js:1:152641
    at Array.forEach (<anonymous>)
At first glance, this appears to be the same error as this was originally started for and looks like I will have to roll-back through the Android app again.
