### ISSUE TITLE
Cannot login: Stuck at "Deriving encryption data"

### ISSUE THREAD

**Issue by junoslukan** [etesync/etesync-web#209]
Sometimes when trying to login, I get stuck at the "Deriving encryption data" step. I am using Firefox 87.0 on Ubuntu 20.04.

As soon as I load the page, I notice the following error in the console:

```
Error during service worker registration: TypeError: ServiceWorker script at https://pim.etesync.com/service-worker.js for scope https://pim.etesync.com/ threw an exception during script evaluation. registerServiceWorker.ts:80:14
    ml registerServiceWorker.ts:80
    (Async: promise callback)
    ml registerServiceWorker.ts:79
    548 registerServiceWorker.ts:44
    (Async: EventListener.handleEvent)
    548 registerServiceWorker.ts:39
    548 index.tsx:45
    Webpack 6
```

I tried removing cookies and site data to no avail.

**Comment by Toasterbirb** [comment]
I also got this issue and simply refreshing the page and trying again fixed it

**Comment by tebeliment** [comment]
I haven't been able to access my data for months. It's been stuck at "Deriving encryption data."

**Comment by arichiardi** [comment]
I got this error and after a refresh (on Chromium) I see

Refused to load the script 'https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' blob:". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

```
(anonymous) @ service-worker.js:14
service-worker.js:14 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js' failed to load.
    at https://pim.etesync.com/service-worker.js:14:1
(anonymous) @ service-worker.js:14
registerServiceWorker.ts:80 Error during service worker registration: TypeError: Failed to register a ServiceWorker for scope ('https://pim.etesync.com/') with script ('https://pim.etesync.com/service-worker.js'): ServiceWorker script evaluation failed
```

Is there anything I can try to debug this - I know the webapp is beta but sometimes it is nice to see your data there.
