### ISSUE TITLE
Web Login fails in Firefox

### ISSUE THREAD

**Issue by lucian303** [etesync/etesync-web#212]
In firefox, it doesn't advance past the login screen. In Chrome, it advances to /wizard and eventually logs in after a very long time. This should work in FF too, especially since it's a privacy protecting service, something that's clearly an oxymoron if it only works in Chrome.

**Comment by tasn** [comment]
I use Firefox personally (never used Chrome), and many of our users do too. I'd recommend you try again. Maybe you have a privacy add-on that's blocking something?

**Comment by lucian303** [comment]
This seems to be intermittent. I didn't see anything being blocked. When it's not successful, it makes no more calls after https://api.etebase.com/partner/etesync/api/v1/authentication/login_challenge/ (200 OK). When it is, there's a ton of calls and it works like Chrome.

**Comment by flphotog** [comment]
I have this issue with both firefox and chrome. Actually it is usually very slow and then comes back with an error message like this:
Something went wrong!
Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at WA (https://pim.etesync.com/static/js/2.b050421f.chunk.js:2:1636310)
    at da (https://pim.etesync.com/static/js/2.b050421f.chunk.js:2:1608136)
    at e [as onStateChange] (https://pim.etesync.com/static/js/2.b050421f.chunk.js:2:887982)
    at e.t.handleChangeWrapper (https://pim.etesync.com/static/js/2.b050421f.chunk.js:2:885847)
    at https://pim.etesync.com/static/js/2.b050421f.chunk.js:2:885174
    at es (https://pim.etesync.com/static/js/2.b050421f.chunk.js:2:1639902)
    at Object.notify (https://pim.etesync.com/static/js/2.b050421f.chunk.js:2:885143)
    at e.t.notifyNestedSubs (https://pim.etesync.com/static/js/2.b050421f.chunk.js:2:885779)
    at e.t.handleChangeWrapper (https://pim.etesync.com/static/js/2.b050421f.chunk.js:2:885847)
    at p (https://pim.etesync.com/static/js/2.b050421f.chunk.js:2:979058)
