### ISSUE TITLE
Error: Minified React error #185

### ISSUE THREAD

**Issue by adamryczkowski** [etesync/etesync-web#235]
Hi! I cannot see the calendar in one of my accounts, and get the following error. 

```Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at WA (http://0.0.0.0:8000/static/js/2.b050421f.chunk.js:2:1636310)
    at da (http://0.0.0.0:8000/static/js/2.b050421f.chunk.js:2:1608136)
    at e [as onStateChange] (http://0.0.0.0:8000/static/js/2.b050421f.chunk.js:2:887982)
    at e.t.handleChangeWrapper (http://0.0.0.0:8000/static/js/2.b050421f.chunk.js:2:885847)
    at http://0.0.0.0:8000/static/js/2.b050421f.chunk.js:2:885174
    at es (http://0.0.0.0:8000/static/js/2.b050421f.chunk.js:2:1639902)
    at Object.notify (http://0.0.0.0:8000/static/js/2.b050421f.chunk.js:2:885143)
    at e.t.notifyNestedSubs (http://0.0.0.0:8000/static/js/2.b050421f.chunk.js:2:885779)
    at e.t.handleChangeWrapper (http://0.0.0.0:8000/static/js/2.b050421f.chunk.js:2:885847)
    at p (http://0.0.0.0:8000/static/js/2.b050421f.chunk.js:2:979058)```

This happens on one of my etesync acconts. I suspect some data stored there to be broken as I can no longer synchronize this particular account, but I have no idea how to verify it. I thought I could sort things out with etesync-web...

**Comment by tasn** [comment]
What's the error you're getting on other clients?

**Comment by Millesimus** [comment]
I'm experiencing the same issue in etesync-web. The web client reports "99+" errors (bubble in the upper right corner). It looks as if those errors were all `invalid date-time value: "--T:-:-T::"` (not sure if related to the React error). Etesync-dav also reports: `Field validation failed.`
