### ISSUE TITLE
Contact sync issue. Error t is undefined

### ISSUE THREAD

**Issue by loyl1** [etesync/etesync-web#257]
I disabled etesync, then enabled it.  Almost all of my Android contacts disappeared from the app. The app started crashing. Calendar and tasks were ok as far as I can tell.

Contacts seem to be ok at pim.etesync.com.

Cleared data on the app. Calendar and tasks synced ok, many but not all contacts are back (now 24 hours after clearing the app data).

At pim.etesync.com I'm getting the error "t is undefined" 

Any ideas on how I can fix sync?

Thanks in advance

**Comment by loyl1** [comment]
New error on pim.etesync.com: 
Cannot read properties of undefined (reading 'length')

**Comment by loyl1** [comment]
The android app errors: 
> <@fuhgeddaboudit:matrix.org> Etesync android crashes when trying to submit verbose logs. I copied what was there and paste it here:
> --- BEGIN DEBUG INFO ---
> SOFTWARE INFORMATION
> EteSync version: 2.3.0 (20300) 
> Installed from: com.machiav3lli.fdroid
> CONFIGURATION
> Power saving disabled: yes
> android.permission.READ_CONTACTS permission: granted
> android.permission.WRITE_CONTACTS permission: granted
> android.permission.READ_CALENDAR permission: granted
> android.permission.WRITE_CALENDAR permission: granted
> org.dmfs.permission.READ_TASKS permission: denied
> org.dmfs.permission.WRITE_TASKS permission: denied
> org.tasks.permission.READ_TASKS permission: granted
> org.tasks.permission.WRITE_TASKS permission: granted
> System-wide synchronization: automatically
> Account: tom111
>   Address book sync. interval: 60 min
>   Calendar     sync. interval: 60 min
>   OpenTasks    sync. interval: —
>   Tasks.org    sync. interval: 60 min
>   WiFi only: false
>   [CardDAV] Contact group method: GROUP_VCARDS
>            Manage calendar colors: true
> Address book account: Not used (tom111 pt)
>   Main account: Account {name=tom111, type=com.etesync.syncadapter}
>   URL: removed
>   Sync automatically: true
> Address book account: Thomas Contacts (tom111 Px)
>   Main account: Account {name=tom111, type=com.etesync.syncadapter}
>   URL: removed
>   Sync automatically: true
> Address book account: Tom Contacts (tom111 te)
>   Main account: Account {name=tom111, type=com.etesync.syncadapter}
>   URL: removed
>   Sync automatically: true
> Address book account: Lori Contacts (tom111 ta)
>   Main account: Account {name=tom111, type=com.etesync.syncadapter}
>   URL: removed
>   Sync automatically: true
> SQLITE DUMP
> android_metadata
> 	|  locale |
> 	|  en_US |
> ----------
> settings
> 	|  setting | value |
> ----------
> SERVICES DUMP
> JOURNALS DUMP
> SYSTEM INFORMATION
> Android version: 13 (TP1A.221005.002.2022110400)
> Device: Google Pixel 4a (sunfish)
> --- END DEBUG INFO ---

2022-11-05 12:23:46 14 [com.etesync.syncadapter.AccountSettings] Account tom111 has version 2, current version: 2
2022-11-05 12:23:46 14 [com.etesync.syncadapter.utils.TaskProviderHandling] Package (un)installed; Syncing (false) for OpenTasks
2022-11-05 12:23:46 14 [com.etesync.syncadapter.AccountSettings] Account tom111 has version 2, current version: 2
2022-11-05 12:23:46 14 [com.etesync.syncadapter.utils.TaskProviderHandling] Package (un)installed; Syncing (true) for TasksOrg

**Comment by loyl1** [comment]
pim.etesync.com new error log:
> <@fuhgeddaboudit:matrix.org> 2022-11-05 12:23:46 14 [com.etesync.syncadapter.AccountSettings] Account tom111 has version 2, current version: 2
> 2022-11-05 12:23:46 14 [com.etesync.syncadapter.utils.TaskProviderHandling] Package (un)installed; Syncing (false) for OpenTasks
> 2022-11-05 12:23:46 14 [com.etesync.syncadapter.AccountSettings] Account tom111 has version 2, current version: 2
> 2022-11-05 12:23:46 14 [com.etesync.syncadapter.utils.TaskProviderHandling] Package (un)installed; Syncing (true) for TasksOrg

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Etebase.js:2:697050
    at Array.reduce (<anonymous>)
    at Etebase.js:2:697031
    at e.<anonymous> (Etebase.js:2:697009)
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:293:22)
    at Generator.next (runtime.js:118:21)
    at n (asyncToGenerator.js:3:20)
    at A (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
(anonymous) @ Etebase.js:2
(anonymous) @ Etebase.js:2
(anonymous) @ Etebase.js:2
c @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
n @ asyncToGenerator.js:3
A @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Etebase.js:2
(anonymous) @ Etebase.js:2
c @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
n @ asyncToGenerator.js:3
A @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Etebase.js:2
(anonymous) @ Etebase.js:2
c @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
n @ asyncToGenerator.js:3
A @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Etebase.js:2
(anonymous) @ CollectionChangeEntries.tsx:33
c @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
A @ asyncToGenerator.js:25
Promise.then (async)
(anonymous) @ CollectionChangeEntries.tsx:56
iA @ react-dom.production.min.js:211
ps @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ui @ react-dom.production.min.js:122
ds @ react-dom.production.min.js:257
(anonymous) @ react-dom.production.min.js:256
L @ scheduler.production.min.js:17
E.port1.onmessage @ scheduler.production.min.js:14

TAsn (EteSync):
