### ISSUE TITLE
pim.etesync.com new-contact submission ("save" button) has no response; js console shows "422 (Unprocessable Content)" error

### ISSUE THREAD

**Issue by jzacsh** [etesync/etesync-web#277]
when I click "save" to submit a new contact form-entry, I see nothing happen on the page. When I try again with js console open I see this:

```
actions.ts:117
    POST
    https://api.etebase.com/partner/etesync/api/v1/collection/67lB_3nrGMYwIH5kMfcN3HMyYeslJMeW/item/batch/
    422
    (Unprocessable Content)
```

Both in chrome `Version 125.0.6422.141 (Official Build) (64-bit)` and in firefox `126.0 (64-bit)`

### more debug details

I saved a HAR in case it's helpful. Just ping me directly if you need it. Also more JS console output:

<details><summary>more of a dump from JS Console</summary>

```js
actions.ts:117 
 POST https://api.etebase.com/partner/etesync/api/v1/collection/67lB_3nrGMYwIH5kMfcN3HMyYeslJMeW/item/batch/ 422 (Unprocessable Content)

Etebase.js:2 Uncaught (in promise) 
Error: 422 [object Object],[object Object]
    at new n (Etebase.js:2:691582)
    at n.<anonymous> (createSuper.js:14:24)
    at new n (Etebase.js:2:691639)
    at n.<anonymous> (Etebase.js:2:703376)
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:293:22)
    at Generator.next (runtime.js:118:21)
    at n (asyncToGenerator.js:3:20)
    at A (asyncToGenerator.js:25:9)
Etebase.js:2 Uncaught 
TypeError: input cannot be null or undefined
    at y (Etebase.js:2:134548)
    at v (Etebase.js:2:134592)
    at C (Etebase.js:2:134655)
    at Object.c [as to_base64] (Etebase.js:2:133099)
    at Module._ (Etebase.js:2:686911)
    at construct.ts:96:31
    at immutable.es.js:2356:29
    at immutable.es.js:2374:16
    at Bt.iterate (immutable.es.js:2786:10)
    at vt.iterate.Ct.iterate (immutable.es.js:2778:22)
Etebase.js:2 Uncaught (in promise) 
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at Q (Etebase.js:2:5574)
    at e.setBuffer (Etebase.js:2:16149)
    at Module.Y (Etebase.js:2:25085)
    at F (Etebase.js:2:687210)
    at Function.value (Etebase.js:2:700185)
    at e.value (Etebase.js:2:715538)
    at etebase-helpers.ts:34:26
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:293:22)

```

</details>

**Comment by tasn** [comment]
Whoops. Can you show the actual 422 response? What's the actual error the server returns (shouldn't contain any sensitive information). Additionally, see the request itself (you can redact the sensitive looking "values" of the json, just keep the "keys" so I can see structure).

Once you provide these though I can surely fix it in 5mins.

**Comment by jzacsh** [comment]
Oh both the payload and response looked like ciphertext to me (and/or encoded content). Do you mind if I just send it to you directly?

**Comment by jzacsh** [comment]
here's the response from the HAR I saved:

```json
        "response": {
          "status": 422,
          "statusText": "",
          "httpVersion": "http/2.0",
          "headers": [
            {
              "name": "access-control-allow-credentials",
              "value": "true"
            },
            {
              "name": "access-control-allow-origin",
              "value": "https://pim.etesync.com"
            },
            {
              "name": "content-length",
              "value": "2763"
            },
            {
              "name": "content-type",
              "value": "application/msgpack"
            },
            {
              "name": "date",
              "value": "Thu, 13 Jun 2024 16:38:11 GMT"
            },
            {
              "name": "server",
              "value": "nginx"
            },
            {
              "name": "vary",
              "value": "Origin, Origin"
            }
          ],
          "cookies": [],
          "content": {
            "size": 2763,
            "mimeType": "application/msgpack",
            "text": "gaZkZXRhaWyShKR0eXBlp21pc3NpbmejbG9jlKRib2R5pWl0ZW1zAK1lbmNyeXB0aW9uS2V5o21zZ65GaWVsZCByZXF1aXJlZKVpbnB1dISjdWlk2SAtSHktTmpZYXl2QktmWUp6VTNZeWNWVC1VVFNHMWplRad2ZXJzaW9uAaRldGFnwKdjb250ZW50hKN1aWS2YS15Q0VXRm5XcXFIazJrS0ZCZFAxZ6RtZXRhxFQY9zkAkZ5vRwtEyIEtaRmDO3SHJjNxqFrJxqRnVTy+38MMtiqEHPR6fSYupfGsbQQfMs/DHTrp1fcmVGxc8QsKaPlmHsTn5qx4ArCXAlpsgQKwiHynZGVsZXRlZMKmY2h1bmtzkZLZKzZFeThvajY0Q21QcnlyTnhEOGJMRDJvOURUSndCek1nVEJqUTlfaXpFQnfFBChCQJrqo7mljyNGQN1981DWH4j0kTc26aw5Gel2l+HnjkYZE0hwTyery0RJJM8ltQyQOR9rtnKOcYrW6x4lnlJ8cTh7Qro6c9ku+uzKMRQxXBLFTvCirdwEMU3p8YVgTwPDXVEHGj3XolqzXrvXV8rQlThAVuk/vTIoPSlMHVT23K7lDpiZw64PdHwtBI5ODPCL+T+zDI6BLSccAKWlEo/DPip3s/0ygbLQzjImIzQMtnOS3RIBzLL56MIKKKCqsRZJwSxBBZvsbkbd6S9LH7J6kpaphFfb7ZhbgQ0KIviVH5QBBehp6V54iPp/U8vf+JuSdg9sNhCGbmj0+hBVMQGVOQ7UCyuY2SxHmqKlqFUpwyI+rRWxRiaeSQT063L9stt9YkfXED9I3Rez/ajcjBwVfRE3FWpUBhlM84Cw3VDOaRkwOw6JAJ0wGGsNOdh24i9lr4WZu7fYQfaD9ckjcu9aO62WWHXMHdzPnSUQCxFidysI7IapunKcWEhH6KQelql+Ltvxe4QFzvVV6Xm1EuicpHp5FLgLuqfmK8WDQGKnX9wWw8Utf0X1LBMDyJpvEIq750tfVeiAYCqQPg9dX4kailI8kNRwNrk7Tp5UFdxXDm+OSOOqjVcCTC9H5wc3xkoqixs54YleCbv/SmT02EuCuYDMvSGWlYvqg8LUSXsO4XvgJui30Rxc4Wubrf5UGuFd0JiNcga9f13wJ2EYIKLZtVuRDYVhtvT3CoDuKEtGuCIOwMsUw7dN1YvGVJL3lVFFzqiWBaYg2jsqiBWSRQ0bZ0WsHPgT0SKA1dBI1tt/oNbhdn26L3h2akA9vRcVNQI2pmVDaVvZQbBNltKfcjEGftVpMSv+u3NohzId0Vro09z45kKmX8IQfGu+k+Lawog6iRjfd4WTbbtjxwFTppOL9fxaGvEuWmX+NArd/HCVFrf4Ym9NSf0Lswvk9iOdYKlNrUEfW78tL/m/2MeOu2OnoeWjnBTeEjDwLutcqR0uhMqCCse7hYBsOC9KyEF62XSZvygdxbED7M37kurfwlF990Qz5Yi/R9OjUQ/fbDJgfn+acDRc4oxZ1hUQ5BfWBjgm9a9+tDDPiN66pImJ+MWWrWnGySvYfVSedlzdErVlc0v3rIZ8EJ6wI5uffwJiUmbA3j37eCSiIqcXRxuzOX+BKClIoobbVD+NGvjGgtwjHy/iGrDEYiraoTJyyVrZE+Fn0uDBDQPs9snbmTS6eQPBj5uwlSzfO3ZNfx6JtIzma3RXJtdMak3JeEqlefEGGStin0n3niaYdIlUXv6m0Z3q6N/DFFdJ2JLcSHryKRyY0oNIqvQUGBKAgdnz20FTkp67vTS/jh8wey4bEVQS2dykZY08m5EqF/UO6/sANFpZU1MyAPbAI13zL17WPqXmNVMSC+MAWuRD9YSkdHlwZadtaXNzaW5no2xvY5KkYm9keaRkZXBzo21zZ65GaWVsZCByZXF1aXJlZKVpbnB1dIGlaXRlbXORhKN1aWTZIC1IeS1OallheXZCS2ZZSnpVM1l5Y1ZULVVUU0cxamVFp3ZlcnNpb24BpGV0YWfAp2NvbnRlbnSEo3VpZLZhLXlDRVdGbldxcUhrMmtLRkJkUDFnpG1ldGHEVBj3OQCRnm9HC0TIgS1pGYM7dIcmM3GoWsnGpGdVPL7fwwy2KoQc9Hp9Ji6l8axtBB8yz8MdOunV9yZUbFzxCwpo+WYexOfmrHgCsJcCWmyBArCIfKdkZWxldGVkwqZjaHVua3ORktkrNkV5OG9qNjRDbVByeXJOeEQ4YkxEMm85RFRKd0J6TWdUQmpROV9pekVCd8UEKEJAmuqjuaWPI0ZA3X3zUNYfiPSRNzbprDkZ6XaX4eeORhkTSHBPJ6vLREkkzyW1DJA5H2u2co5xitbrHiWeUnxxOHtCujpz2S767MoxFDFcEsVO8KKt3AQxTenxhWBPA8NdUQcaPdeiWrNeu9dXytCVOEBW6T+9Mig9KUwdVPbcruUOmJnDrg90fC0Ejk4M8Iv5P7MMjoEtJxwApaUSj8M+Knez/TKBstDOMiYjNAy2c5LdEgHMsvnowgoooKqxFknBLEEFm+xuRt3pL0sfsnqSlqmEV9vtmFuBDQoi+JUflAEF6GnpXniI+n9Ty9/4m5J2D2w2EIZuaPT6EFUxAZU5DtQLK5jZLEeaoqWoVSnDIj6tFbFGJp5JBPTrcv2y231iR9cQP0jdF7P9qNyMHBV9ETcValQGGUzzgLDdUM5pGTA7DokAnTAYaw052HbiL2WvhZm7t9hB9oP1ySNy71o7rZZYdcwd3M+dJRALEWJ3Kwjshqm6cpxYSEfopB6WqX4u2/F7hAXO9VXpebUS6JykenkUuAu6p+YrxYNAYqdf3BbDxS1/RfUsEwPImm8QirvnS19V6IBgKpA+D11fiRqKUjyQ1HA2uTtOnlQV3FcOb45I46qNVwJML0fnBzfGSiqLGznhiV4Ju/9KZPTYS4K5gMy9IZaVi+qDwtRJew7he+Am6LfRHFzha5ut/lQa4V3QmI1yBr1/XfAnYRggotm1W5ENhWG29PcKgO4oS0a4Ig7AyxTDt03Vi8ZUkveVUUXOqJYFpiDaOyqIFZJFDRtnRawc+BPRIoDV0EjW23+g1uF2fboveHZqQD29FxU1AjamZUNpW9lBsE2W0p9yMQZ+1WkxK/67c2iHMh3RWujT3PjmQqZfwhB8a76T4trCiDqJGN93hZNtu2PHAVOmk4v1/Foa8S5aZf40Ct38cJUWt/hib01J/QuzC+T2I51gqU2tQR9bvy0v+b/Yx467Y6eh5aOcFN4SMPAu61ypHS6EyoIKx7uFgGw4L0rIQXrZdJm/KB3FsQPszfuS6t/CUX33RDPliL9H06NRD99sMmB+f5pwNFzijFnWFRDkF9YGOCb1r360MM+I3rqkiYn4xZatacbJK9h9VJ52XN0StWVzS/eshnwQnrAjm59/AmJSZsDePft4JKIipxdHG7M5f4EoKUiihttUP40a+MaC3CMfL+IasMRiKtqhMnLJWtkT4WfS4MENA+z2yduZNLp5A8GPm7CVLN87dk1/Hom0jOZrdFcm10xqTcl4SqV58QYZK2KfSfeeJph0iVRe/qbRnero38MUV0nYktxIevIpHJjSg0iq9BQYEoCB2fPbQVOSnru9NL+OHzB7LhsRVBLZ3KRljTybkSoX9Q7r+wA0WllTUzIA9sAjXfMvXtY+peY1UxIL4wBa5EP1",
            "encoding": "base64"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 2932,
          "_error": null
        },
```

**Comment by tasn** [comment]
I'm pretty sure it's fixed in https://github.com/etesync/server/commit/f35b4b94e5a75bbc8cc41749ca2e3800bbc7a44e

It happened because pydantic v2 changed the behavior in a few ways (for the better fwiw) and I missed a few things when upgrading.

Can you try now? The server should be running the fixed version!

**Comment by jzacsh** [comment]
confirmed fixed. Thanks for the quick deploy!

**Comment by tasn** [comment]
Thanks for all of the helpful debug info!
