### ISSUE TITLE
Add support for recurring events

### ISSUE THREAD

**Issue by neurokrish** [etesync/etesync-web#50]
Can't seem to find a way to add recurring events. Will be very useful for events like birthdays..

**Comment by tasn** [comment]
Definitely. FWIW they currently show correctly, you just can't edit them.

**Comment by neurokrish** [comment]
Doesn't work for me. I have a birthday calendar with recurring yearly events imported. When I click those events, it throws up an error saying "something went wrong" and that an "event should be defined!" with something under "stack trace". No such errors occur for regular calendar events. Am I missing something?

**Comment by neurokrish** [comment]
OK, I misread your comment. Looks like you know the issue. Yes, I can see the recurring events just fine but when I click on it, I get an error. Guess that's what you meant by "can't edit them". Hope you can push a fix for this.

**Comment by tasn** [comment]
I'm actually not familiar with the crash. It should show a nice error message. Could you maybe put the backtrace here? Thanks!

**Comment by Nuntius0** [comment]
```
Error: Event should be defined!
    at t.value (https://client.etesync.com/static/js/main.59c3899d.chunk.js:1:36954)
    at Mo (https://client.etesync.com/static/js/2.88819104.chunk.js:1:763666)
    at Co (https://client.etesync.com/static/js/2.88819104.chunk.js:1:763459)
    at Io (https://client.etesync.com/static/js/2.88819104.chunk.js:1:767316)
    at Ya (https://client.etesync.com/static/js/2.88819104.chunk.js:1:786901)
    at qa (https://client.etesync.com/static/js/2.88819104.chunk.js:1:787285)
    at Ts (https://client.etesync.com/static/js/2.88819104.chunk.js:1:793831)
    at ks (https://client.etesync.com/static/js/2.88819104.chunk.js:1:793211)
    at Ds (https://client.etesync.com/static/js/2.88819104.chunk.js:1:799862)
    at Tn (https://client.etesync.com/static/js/2.88819104.chunk.js:1:732363)
```
I'm getting this too. Weirdly enough, only for some recurring events but not all, and sometimes only when clicking on the event from the week view but not from the month view.

**Comment by tasn** [comment]
This is a recent regression, I swear it used to work. I wonder what it's about.

**Comment by tasn** [comment]
Btw, @Nuntius0, let's talk about this issue in #56. This ticket is about adding a way to add recurring events.
